theme: jekyll-theme-minimal
use_logo: true
logo: https://raw.githubusercontent.com/allyomalley/VoteTracker/master/Icon-App-83.5x83.5@2x.png
avatar: https://raw.githubusercontent.com/allyomalley/VoteTracker/master/avatar.png
